model:
  class: LGBModel
  params:
    colsample_bytree: 0.8
    learning_rate: 0.02
    max_depth: 8
    early_stopping_rounds: 80
    num_boost_round: 1000
    loss: mse
    subsample: 0.8
    reg_alpha: 0.1
    reg_lambda: 0.1
    min_child_samples: 50
    seed: 42

markets:
  cn: {}
  us: {}
  jp: {}
